spring.datasource.url=jdbc:postgresql://postgres:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=123

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/devtrends
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/devtrends/protocol/openid-connect/certs
