spring.application.name=DevTrendsExplorer

server.port=8090

# Database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=123

logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.hibernate.type=trace
logging.level.org.hibernate.stat=debug
spring.liquibase.change-log=classpath:changelog/db.changelog-master.yaml
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Keycloak OAuth2
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/devtrends
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/devtrends/protocol/openid-connect/certs

# Documentation
springdoc.swagger-ui.oauth.client-id=devtrends-frontend